# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  #product: Collectors
  #version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:
    - title: Overview
      url: /Introduction.html
      output: web, pdf
      
  - title: Hygieia Dashboard
    output: web, pdf
    folderitems:
    - title: Signup and Login
      url: signup.html
      output: web, pdf
    - title: Select Your Dashboard
      url: select_dashboard.html
      output: web, pdf
    
  - title: Configure the Dashboard
    output: web, pdf
    folderitems:
    - title: Dashboard Views
      url: dashboard_views.html
      output: web, pdf
    - title: Widget View
      url: widget_view.html
      output: web, pdf
    - title: Product View
      url: product_view.html
      output: web, pdf
    - title: Pipeline View
      url: pipeline_view.html
      output: web, pdf
    - title: Cloud View
      url: cloud_view.html
      output: web, pdf   

  - title: Dashboard Administration
    output: web, pdf
    folderitems:
    - title: Administration Options
      url: dashboard_administration.html
      output: web, pdf
    